### ISSUE TITLE
Coefficient plots won't facet

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/Dissertation#3]
Currently ggplot does not support free facet scales with `coord_flip()`, so I have to fake facets with `gridExtra`:

![1-coefs-int](https://cloud.githubusercontent.com/assets/73663/13530296/b69d59e0-e1ee-11e5-852c-aca1ea28614c.png)

But doing that means I lose the axis consistency I'd get from using facets—i.e., each pseudo facet currently has 0 at a different location and uses different a min/max in the scale. 

With ggplot2 2.0's support of extensions, [ggstance](https://github.com/lionel-/ggstance) seems promising (especially `geom_pointrangeh`), but it currently either reports errors about undefined `ymin` and `ymax` aesthetics (related to [this](https://github.com/lionel-/ggstance/issues/3)), or when using the development version of ggplot where this is apparently fixed ([here](https://github.com/hadley/ggplot2/pull/1564)).

Revisit these plots once the development dust has settled and ggstance and ggplot work together again?

**Comment by sahirbhatnagar** [comment]
+1

**Comment by andrewheiss** [comment]
This works nowadays:

![1-coefs-bayes](https://cloud.githubusercontent.com/assets/73663/18898216/1c3bc61c-84fe-11e6-95ad-e15859ea65cb.png)
